// AUTOGENERATED from VV canonical IRs via derive_delay_tables.py.
// Do not edit by hand — regenerate if VV reference changes.
//
// Per-preset DattorroTank delay-line lengths in samples at 48 kHz,
// derived from the prominent early-reflection peaks in VV's
// 50-take averaged canonical IR for each preset. Using these
// per-preset delays makes DV's modal signature match VV's
// instead of sharing one shared modal fingerprint across all presets.
//
// Slot layout (index → architecture position, sorted shortest→longest):
//   [0] ap1
//   [1] dense_0
//   [2] dense_1
//   [3] ap2
//   [4] dense_2
//   [5] delay1
//   [6] delay2

#pragma once
#include <cstddef>
#include <string>

namespace dusk::baked {

inline constexpr int kVvDelaySlotCount = 7;

struct PresetDelayEntry {
    const char* presetName;
    int delays[kVvDelaySlotCount];
};

inline constexpr int kVvPresetDelayCount = 53;

inline constexpr PresetDelayEntry kVvPresetDelays[kVvPresetDelayCount] = {
    { "A Plate", { 2296, 2666, 2761, 3127, 3248, 3346, 3427 } },
    { "Ambience Plate", { 1899, 2145, 2203, 2628, 2977, 3131, 3213 } },
    { "Ambience Tiled Room", { 673, 745, 886, 1057, 1138, 1268, 1346 } },
    { "Ambience", { 1622, 1686, 1860, 2003, 2181, 2351, 2478 } },
    { "Big Ambience Gate", { 3431, 4041, 4520, 4647, 4968, 5138, 5297 } },
    { "Clear Chamber", { 1743, 2558, 2795, 3096, 3231, 3411, 3660 } },
    { "Concert Wave", { 1744, 2008, 2273, 2449, 2608, 2829, 3928 } },
    { "Cross Stick Room", { 815, 920, 1302, 1361, 1442, 1534, 1594 } },
    { "Dark Vocal Room", { 1219, 1363, 1951, 2280, 2457, 3383, 3706 } },
    { "Drum Air", { 464, 569, 885, 950, 1091, 1252, 1332 } },
    { "Drum Plate", { 687, 934, 1128, 1243, 1464, 1569, 1772 } },
    { "Exciting Snare Room", { 819, 1046, 1183, 1262, 1411, 1527, 1792 } },
    { "Fat Drums", { 1904, 2433, 4052, 4185, 4323, 4456, 4581 } },
    { "Fat Plate", { 4898, 5023, 5110, 5421, 5525, 5693, 5841 } },
    { "Fat Snare Hall", { 1445, 1736, 2264, 2572, 3500, 3807, 3863 } },
    { "Fat Snare Room", { 859, 943, 1110, 1210, 1361, 1428, 1527 } },
    { "Gated Snare", { 2617, 2935, 3072, 3431, 3524, 3591, 4350 } },
    { "Homestar Blade Runner", { 2058, 2322, 2587, 2764, 2922, 3142, 3685 } },
    { "Huge Synth Hall", { 5319, 5478, 5583, 5760, 6024, 6289, 6465 } },
    { "Large Ambience", { 2181, 2298, 2742, 2994, 3387, 3679, 3778 } },
    { "Large Chamber", { 1631, 2924, 3915, 4212, 4573, 4644, 5292 } },
    { "Large Gated Snare", { 1881, 2677, 3239, 3298, 3407, 3526, 3732 } },
    { "Large Plate", { 687, 845, 952, 1128, 1374, 1463, 1569 } },
    { "Large Wood Room", { 1533, 1612, 2243, 2666, 2761, 3021, 3128 } },
    { "Live Vox Chamber", { 978, 1197, 1315, 1392, 1561, 1712, 1837 } },
    { "Lively Snare Room", { 546, 837, 885, 1012, 1109, 1304, 1419 } },
    { "Long Dark 70s Snare Room", { 2433, 2826, 3366, 3653, 3907, 4116, 4263 } },
    { "Long Synth Hall", { 1288, 1831, 2519, 3401, 3489, 5354, 5487 } },
    { "Med Ambience", { 1883, 1984, 2367, 2583, 2674, 2920, 3078 } },
    { "Medium Gate", { 2005, 2231, 2324, 2397, 2572, 2628, 2769 } },
    { "Pad Hall", { 5320, 5479, 5584, 5761, 5849, 6025, 6096 } },
    { "Rich Chamber", { 3148, 3229, 3439, 3621, 3828, 4246, 4621 } },
    { "Short Dark Snare Room", { 673, 754, 917, 1038, 1160, 1226, 1322 } },
    { "Short Vocal Ambience", { 1085, 1465, 1570, 1688, 1756, 1860, 1975 } },
    { "Small Ambience", { 1049, 1103, 1430, 1478, 1747, 1850, 1946 } },
    { "Small Chamber1", { 1456, 1533, 1589, 1707, 1782, 1899, 1956 } },
    { "Small Chamber2", { 1498, 1865, 2114, 2231, 2445, 2742, 3097 } },
    { "Small Drum Room", { 1152, 1375, 1505, 1774, 1842, 2094, 2245 } },
    { "Small Vocal Hall", { 1530, 1706, 1949, 2235, 2412, 2571, 2792 } },
    { "Snare Ambience", { 1490, 2118, 2419, 2465, 2670, 2872, 3133 } },
    { "Snare Hall", { 897, 1003, 1180, 1268, 1444, 1514, 1621 } },
    { "Snare Plate", { 3091, 3745, 3865, 3994, 4112, 4849, 5178 } },
    { "Steel Plate", { 935, 1118, 1444, 1729, 1831, 1953, 2086 } },
    { "Thin Plate", { 1210, 1656, 2552, 2650, 2730, 2786, 2892 } },
    { "Tight Ambience Gate", { 2206, 2391, 2461, 2528, 2658, 2712, 2837 } },
    { "Tight Plate", { 679, 832, 1102, 1340, 1424, 1524, 1609 } },
    { "Tiled Room", { 543, 634, 956, 1325, 1390, 1460, 1567 } },
    { "Trip Hop Snare", { 3037, 3160, 3568, 3628, 3893, 4310, 4500 } },
    { "Very Nice Hall", { 2810, 3102, 3663, 3820, 3936, 4093, 6386 } },
    { "Very Small Ambience", { 552, 693, 844, 934, 1137, 1317, 1367 } },
    { "Vocal Hall", { 601, 760, 1042, 1289, 1483, 1571, 1818 } },
    { "Vocal Plate", { 1924, 2188, 2245, 2297, 2406, 2495, 2584 } },
    { "Vox Plate", { 688, 931, 1217, 1394, 1552, 1772, 2136 } },
};

// Returns pointer to delays array for preset, or nullptr if not found.
inline const int* findVvDelaysForPreset(const char* name)
{
    if (!name) return nullptr;
    for (int i = 0; i < kVvPresetDelayCount; ++i)
    {
        const PresetDelayEntry& e = kVvPresetDelays[i];
        // simple strcmp without <cstring> to keep this header light
        const char* a = name;
        const char* b = e.presetName;
        while (*a && *a == *b) { ++a; ++b; }
        if (*a == 0 && *b == 0) return e.delays;
    }
    return nullptr;
}

} // namespace dusk::baked
