// Copyright (C) 2026 Dusk Audio — GNU GPL v3.0 or later (see repository LICENSE).
// Third-party components in the built plugins (DPF — ISC; Dear ImGui — MIT; and
// others) are attributed in plugins/shared-dpf/THIRD_PARTY_LICENSES.md.
//
// PatreonBackersDpf.hpp — framework-free Patreon backer list for DPF/ImGui UIs.
//
// GENERATED by scripts/update-patrons.py — do NOT hand-edit. Mirrors the
// JUCE-typed plugins/shared/PatreonBackers.h so DPF plugins (no JUCE) show the
// same credits. Tiers with no names are skipped by the credits overlay.

#pragma once

#include <vector>

namespace duskdpf
{

struct BackerTier
{
    const char* title;
    std::vector<const char*> names;
};

inline const std::vector<BackerTier>& patreonTiers()
{
    static const std::vector<BackerTier> tiers = {
        { "CHAMPIONS", {} },
        { "PATRONS", { "danboy", "David", "nuertine DIGEL" } },
        { "SUPPORTERS", { "Beau Landry", "Eblen Macari", "Jano", "Manav", "Someone64" } },
        { "HUGS", { "Adrienne", "Andre C", "Benjamin Walker", "Chaumontet Olivier", "Codey", "Dusk Audio", "fennek", "fisHkiD76", "Jon Skarin", "LEONID FEDOROV", "Samantha Druker" } },
        { "PAST SUPPORTERS", { "mister-universe", "S C", "Stefan Windus" } },
    };
    return tiers;
}

} // namespace duskdpf
